merge-configs: Change fish command-not-found message

diff --git a/.local/bin/merge-configs b/.local/bin/merge-configs
--- a/.local/bin/merge-configs
+++ b/.local/bin/merge-configs
@@ -2,6 +2,12 @@
 
 set SKEL_FILES_PATH "$HOME/.local/share/skel"
 
+# override fish's command not found messages
+function fish_command_not_found
+    echo -e "\e[1mError while trying to run the following command\e[0m:" >&2
+    echo "--> $argv" >&2
+end
+
 function mergevars
     argparse i -- $argv
     set file_string $argv
@@ -9,6 +15,9 @@ function mergevars
     # get all marked fields in the file
     for match in (string match -ra -- '\{\{\{.+?\}\}\}' $file_string)
         set field (string trim -c '{}' -- $match)
+        #  we need to reset repl for each iteration so we can test for a field
+        #  that evaluated to nothing
+        set repl
 
         # if i flag was passed, skip on "custom" fields
         if set -q _flag_i && [ "$field" = custom ]
